version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/project
    depends_on:
      - redis
  redis:
    image: redis

  client:
    extends:
      file: ../http/docker-compose.yml
      service: client
